#!/bin/sh

config_lwt () {
    if ocamlfind query lwt_ppx >/dev/null 2>&1
    then
	patch $RECOVER --no-backup-if-mismatch -r - -f -p1 < patches/use-lwt_ppx.patch
    fi
}

case $1 in
    --distclean)
	RECOVER=-R config_lwt
	exit 0
	;;
    *)
	config_lwt
	;;
esac
